packages:
  - "**"
allowBuilds:
  '@parcel/watcher': false
  '@prisma/engines': true
  '@swc/core': false
  cypress: false
  esbuild: false
  prisma: true
  sharp: false
overrides:
  postcss@<8.5.10: '^8.5.15'
  '@hono/node-server@<1.19.13': '^1.19.13'
  d3-color@<3.1.0: '^3.1.0'
